on:
  push:
    branches: [feat/HP-5]
    
name: Get Github Release Data
jobs:
  latest-version:
    name: Get Latest Release
    runs-on: ubuntu-latest
    environment: stage   #For Environment
    steps:
      - uses: actions/checkout@master
      - name: Example of consumption of the output
        run: echo "Hello World"
